apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-testchatbot-oct4-gitops
spec:  
  template:         
    metadata:
      name: dsp-clone-job-testchatbot-oct4-gitops
    spec:  
      serviceAccountName: testchatbot-oct4-dsp-job
      containers:
      - name: initialize-dsp
        image: quay.io/redhat-ai-dev/utils:latest
        command:
        - /bin/bash
        - -c
        - |
          NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
          oc wait -l statefulset=testchatbot-oct4-notebook --for=condition=ready pod --timeout=300s
          oc exec  StatefulSet/testchatbot-oct4-notebook -- git clone https://github.com/jdubrick-ai/testchatbot-oct4
      restartPolicy: Never