apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testchatbot-oct4-gitops
  description: This is GitOps manifest for testchatbot-oct4   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testchatbot-oct4
    janus-idp.io/tekton: testchatbot-oct4 
    backstage.io/kubernetes-id: testchatbot-oct4 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testchatbot-oct4
